### ISSUE TITLE
Missing source code

### ISSUE THREAD

**Issue by ianw172** [TheGameCreators/AGKRepo#27]
Hi,
Source code for some of the agk:: functions is missing from the repository. For example, agk::InitGL(), agk::PlatformInitGL(), agk::PlatformInit()
They are in the platform/windows/lib/AGKWindows64.lib library and AgkIde builds ok in Windows using this lib but fails to build if using AGKWindows64.lib built from source (and I can't build the linux ide as the equivalent library for platform/linux is missing.
Is there any reason for this ?
Thanks.

**Comment by ianw172** [comment]
And if the source is unavailable then can you upload the binary with the functions to AgkIde/platform/linux/Lib/Release64/libAGKLinux.a so I can build the ide for Linux (I know it's no longer supported but everything still builds ok except for the ide).

**Comment by ZaxxanStudios** [comment]
Can you check the file size  of the AGKWindows64.lib you are trying to use

**Comment by ZaxxanStudios** [comment]
The IDE in windows uses the prebuilt version of AGKWindows64.lib and will not work if you try and use the version that you build yourself. I asked for the source code to the prebuilt version several months ago but it doesn't seem like it's available unfortunately.

**Comment by ianw172** [comment]
Thanks for the info. A shame the prebuilt linux library is missing. Did you get any reason why the source for the prebuilt lib has not been uploaded ?

**Comment by ZaxxanStudios** [comment]
I asked a couple of the times but I never got it. I have no idea why though.

**Comment by ianw172** [comment]
They sent me the prebuilt linux lib and now the ide builds and runs ok.
Thanks.

**Comment by ZaxxanStudios** [comment]
Any chance you could upload this to GitHub and do a pull request so that it becomes part of the Repo incase someone else needs it?
